# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

expansion = Expansion.create(bundle_name: "expansion0001", cost: 20)
Card.create(expansion_id: expansion.id, asset_name: "f001")
Card.create(expansion_id: expansion.id, asset_name: "f002")
Card.create(expansion_id: expansion.id, asset_name: "f003")
Card.create(expansion_id: expansion.id, asset_name: "f004")
Card.create(expansion_id: expansion.id, asset_name: "f005")
Card.create(expansion_id: expansion.id, asset_name: "f006")
Card.create(expansion_id: expansion.id, asset_name: "f007")
Card.create(expansion_id: expansion.id, asset_name: "f008")
Card.create(expansion_id: expansion.id, asset_name: "f009")
Card.create(expansion_id: expansion.id, asset_name: "f010")
Card.create(expansion_id: expansion.id, asset_name: "f011")
Card.create(expansion_id: expansion.id, asset_name: "f012")
Card.create(expansion_id: expansion.id, asset_name: "f013")
Card.create(expansion_id: expansion.id, asset_name: "f014")
Card.create(expansion_id: expansion.id, asset_name: "f015")
Card.create(expansion_id: expansion.id, asset_name: "f016")
Card.create(expansion_id: expansion.id, asset_name: "f017")
Card.create(expansion_id: expansion.id, asset_name: "f018")
Card.create(expansion_id: expansion.id, asset_name: "f019")
Card.create(expansion_id: expansion.id, asset_name: "f020")
Card.create(expansion_id: expansion.id, asset_name: "f021")
Card.create(expansion_id: expansion.id, asset_name: "f022")
Card.create(expansion_id: expansion.id, asset_name: "f023")
Card.create(expansion_id: expansion.id, asset_name: "f024")
Card.create(expansion_id: expansion.id, asset_name: "f025")
Card.create(expansion_id: expansion.id, asset_name: "f026")
Card.create(expansion_id: expansion.id, asset_name: "f027")
Card.create(expansion_id: expansion.id, asset_name: "f028")
Card.create(expansion_id: expansion.id, asset_name: "f029")
Card.create(expansion_id: expansion.id, asset_name: "f030")
