name: Test

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up -d db
      - run: docker-compose build
      - run: docker-compose run server rails db:create
      - run: docker-compose run server rails db:migrate
      - run: docker-compose run server bundle exec rspec spec
      - uses: rtCamp/action-slack-notify@v2.0.2
        if: success()
        env:
          SLACK_CHANNEL: simple_social_game_develop
          SLACK_TITLE: Test Failure
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
